// SPDX-License-Identifier: MIT OR Apache-2.0

#![allow(clippy::too_many_arguments)]

use std::fmt;

use iec_diagnostics::{Diagnostic, DiagnosticCode};
use iec_ir::*;
use iec_profile::ImplementationParameters;

const RBCPP_DEFAULT_STRING_CAP: usize = 256;

#[derive(Debug, Clone)]
pub struct COutput {
    pub filename_hint: String,
    pub source: String,
}

#[derive(Debug, Clone, Default)]
pub struct COptions {
    pub implementation: ImplementationParameters,
}

#[derive(Debug, Clone)]
pub enum CEmitError {
    Diagnostics(Vec<Diagnostic>),
    Format(fmt::Error),
    UnsupportedState(String),
    ResourceLimit(String),
}

impl CEmitError {
    pub fn into_diagnostics(self) -> Vec<Diagnostic> {
        match self {
            CEmitError::Diagnostics(diagnostics) => diagnostics,
            CEmitError::Format(_) => vec![Diagnostic::error(
                DiagnosticCode::Unsupported,
                "C generation failed while writing output",
                None,
            )],
            CEmitError::UnsupportedState(message) | CEmitError::ResourceLimit(message) => {
                vec![Diagnostic::error(
                    DiagnosticCode::Unsupported,
                    message,
                    None,
                )]
            }
        }
    }
}

impl From<fmt::Error> for CEmitError {
    fn from(error: fmt::Error) -> Self {
        CEmitError::Format(error)
    }
}

pub(crate) struct CEmitter<'a> {
    writer: &'a mut dyn fmt::Write,
    bytes_written: usize,
    failed: bool,
}

impl<'a> CEmitter<'a> {
    pub(crate) fn new(writer: &'a mut dyn fmt::Write) -> Self {
        Self {
            writer,
            bytes_written: 0,
            failed: false,
        }
    }

    pub(crate) fn write_fmt(&mut self, args: fmt::Arguments<'_>) {
        self.push_str(&args.to_string());
    }

    pub(crate) fn push_str(&mut self, text: &str) {
        if self.failed {
            return;
        }
        if self.writer.write_str(text).is_ok() {
            self.bytes_written += text.len();
        } else {
            self.failed = true;
        }
    }

    pub(crate) fn len(&self) -> usize {
        self.bytes_written
    }

    pub(crate) fn check(&self) -> Result<(), CEmitError> {
        if self.failed {
            Err(CEmitError::Format(fmt::Error))
        } else {
            Ok(())
        }
    }
}

macro_rules! c_write {
    ($out:expr, $($arg:tt)*) => {{
        let _ = $out.write_fmt(format_args!($($arg)*));
    }};
}

macro_rules! c_writeln {
    ($out:expr $(,)?) => {{
        $out.push_str("\n");
    }};
    ($out:expr, $($arg:tt)*) => {{
        let _ = $out.write_fmt(format_args!($($arg)*));
        $out.push_str("\n");
    }};
}

pub fn generate_c(
    project: &Project,
    program_name: Option<&str>,
) -> Result<COutput, Vec<Diagnostic>> {
    try_generate_c(project, program_name).map_err(CEmitError::into_diagnostics)
}

pub fn generate_c_with_options(
    project: &Project,
    program_name: Option<&str>,
    options: &COptions,
) -> Result<COutput, Vec<Diagnostic>> {
    try_generate_c_with_options(project, program_name, options)
        .map_err(CEmitError::into_diagnostics)
}

pub fn try_generate_c(
    project: &Project,
    program_name: Option<&str>,
) -> Result<COutput, CEmitError> {
    try_generate_c_with_options(project, program_name, &COptions::default())
}

pub fn try_generate_c_with_options(
    project: &Project,
    program_name: Option<&str>,
    options: &COptions,
) -> Result<COutput, CEmitError> {
    let Some(program) = find_program(project, program_name) else {
        return Err(CEmitError::Diagnostics(vec![Diagnostic::error(
            DiagnosticCode::Unsupported,
            "no PROGRAM POU found for C generation",
            None,
        )]));
    };

    let mut source = String::new();
    let mut out = CEmitter::new(&mut source);
    c_writeln!(out, "/*");
    c_writeln!(out, " * Generated by RoboC++ (rbcpp).");
    c_writeln!(out, " * SPDX-License-Identifier: MIT OR Apache-2.0");
    c_writeln!(out, " *");
    c_writeln!(
        out,
        " * This generated file follows the RoboC++ project license unless the"
    );
    c_writeln!(
        out,
        " * input project or surrounding integration imposes additional terms."
    );
    c_writeln!(out, " */");
    c_writeln!(out, "#include <math.h>");
    c_writeln!(out, "#include <stdbool.h>");
    c_writeln!(out, "#include <stdint.h>");
    c_writeln!(out, "#include <stddef.h>");
    c_writeln!(out, "#include <stdio.h>");
    c_writeln!(out, "#include <stdlib.h>");
    c_writeln!(out, "#include <string.h>");
    c_writeln!(out, "#ifndef RBCPP_CYCLE_MS");
    c_writeln!(out, "#define RBCPP_CYCLE_MS 1");
    c_writeln!(out, "#endif");
    c_writeln!(out, "#ifndef RBCPP_STRING_CAP");
    c_writeln!(out, "#define RBCPP_STRING_CAP 256");
    c_writeln!(out, "#endif");
    c_writeln!(out, "#if defined(__GNUC__) || defined(__clang__)");
    c_writeln!(out, "#define RBCPP_UNUSED __attribute__((unused))");
    c_writeln!(out, "#else");
    c_writeln!(out, "#define RBCPP_UNUSED");
    c_writeln!(out, "#endif");
    c_writeln!(out, "#define RBCPP_ABS(a) (((a) < 0) ? -(a) : (a))");
    c_writeln!(out, "#define RBCPP_MIN(a, b) (((a) < (b)) ? (a) : (b))");
    c_writeln!(out, "#define RBCPP_MAX(a, b) (((a) > (b)) ? (a) : (b))");
    c_writeln!(
        out,
        "#define RBCPP_LIMIT(mn, in, mx) RBCPP_MIN(RBCPP_MAX((in), (mn)), (mx))"
    );
    c_writeln!(out, "#define RBCPP_SEL(g, a, b) ((g) ? (b) : (a))");
    c_writeln!(
        out,
        "static RBCPP_UNUSED int64_t rbcpp_shl64(int64_t value, int64_t shift) {{ if (shift < 0 || shift >= 64) {{ return 0; }} return (int64_t)(((uint64_t)value) << (uint64_t)shift); }}"
    );
    c_writeln!(
        out,
        "static RBCPP_UNUSED int64_t rbcpp_shr64(int64_t value, int64_t shift) {{ if (shift < 0 || shift >= 64) {{ return 0; }} return (int64_t)(((uint64_t)value) >> (uint64_t)shift); }}"
    );
    c_writeln!(
        out,
        "static RBCPP_UNUSED int64_t rbcpp_rol64(int64_t value, int64_t shift) {{ if (shift < 0) {{ return 0; }} uint64_t n = ((uint64_t)shift) & 63u; uint64_t v = (uint64_t)value; return (int64_t)((v << n) | (v >> ((64u - n) & 63u))); }}"
    );
    c_writeln!(
        out,
        "static RBCPP_UNUSED int64_t rbcpp_ror64(int64_t value, int64_t shift) {{ if (shift < 0) {{ return 0; }} uint64_t n = ((uint64_t)shift) & 63u; uint64_t v = (uint64_t)value; return (int64_t)((v >> n) | (v << ((64u - n) & 63u))); }}"
    );
    c_writeln!(out);
    emit_communication_abi(&mut out);
    emit_target_abi(&mut out);
    emit_bcd_helpers(&mut out);
    emit_date_time_helpers(&mut out);
    emit_string_helpers(&mut out);
    emit_data_type_declarations(&mut out, project);
    for function in project
        .pous()
        .filter(|pou| matches!(&pou.kind, PouKind::Function { .. }))
    {
        emit_function_pou(&mut out, function, project);
        c_writeln!(out);
    }
    c_writeln!(out, "typedef struct {{");
    c_writeln!(out, "    rbcpp_comm_hook rbcpp_comm;");
    c_writeln!(out, "    void *rbcpp_comm_ctx;");
    c_writeln!(out, "    rbcpp_target_hooks rbcpp_target;");
    c_writeln!(out, "    void *rbcpp_target_ctx;");
    c_writeln!(out, "    uint64_t rbcpp_cycle;");
    for (var, _) in program_vars_with_retain(program, project) {
        let declared = emit_function_block_state_declaration(
            &mut out,
            &var.name.original,
            &var.type_spec,
            project,
        ) || emit_aggregate_state_declaration(&mut out, var, project);
        if !declared {
            c_writeln!(
                out,
                "    {} {};",
                c_storage_type(project, &var.type_spec),
                sanitize_c_ident(&var.name.original)
            );
        }
    }
    if let Some(sfc) = &program.body.sfc {
        for step in &sfc.steps {
            c_writeln!(out, "    bool {};", sfc_step_field(&step.name));
        }
        for key in sfc_action_control_keys(sfc) {
            c_writeln!(out, "    bool {};", sfc_action_field_from_key(&key));
            c_writeln!(
                out,
                "    bool {};",
                sfc_action_previous_field_from_key(&key)
            );
            c_writeln!(
                out,
                "    int64_t {};",
                sfc_action_elapsed_field_from_key(&key)
            );
        }
    }
    for direct in direct_variable_refs_for_program(program) {
        c_writeln!(
            out,
            "    {} {};",
            c_storage_type(project, &direct.type_spec),
            sanitize_c_ident(&direct.location)
        );
    }
    let state_type = format!("{}_state", sanitize_c_ident(&program.name.original));
    c_writeln!(out, "}} {state_type};");
    emit_debug_metadata(&mut out, program, project, &state_type);

    c_writeln!(out);
    c_writeln!(
        out,
        "void {}_init({} *s) {{",
        sanitize_c_ident(&program.name.original),
        state_type
    );
    c_writeln!(out, "    s->rbcpp_comm = NULL;");
    c_writeln!(out, "    s->rbcpp_comm_ctx = NULL;");
    c_writeln!(
        out,
        "    memset(&s->rbcpp_target, 0, sizeof(s->rbcpp_target));"
    );
    c_writeln!(out, "    s->rbcpp_target_ctx = NULL;");
    c_writeln!(out, "    s->rbcpp_cycle = 0;");
    for (var, _) in program_vars_with_retain(program, project) {
        emit_state_initialization(&mut out, var, project);
    }
    if let Some(sfc) = &program.body.sfc {
        emit_sfc_initialization(&mut out, sfc);
    }
    c_writeln!(out, "}}");

    c_writeln!(out);
    c_writeln!(
        out,
        "void {}_set_comm_hook({} *s, rbcpp_comm_hook hook, void *ctx) {{",
        sanitize_c_ident(&program.name.original),
        state_type
    );
    c_writeln!(out, "    s->rbcpp_comm = hook;");
    c_writeln!(out, "    s->rbcpp_comm_ctx = ctx;");
    c_writeln!(out, "}}");

    c_writeln!(out);
    c_writeln!(
        out,
        "void {}_set_target_hooks({} *s, const rbcpp_target_hooks *hooks, void *ctx) {{",
        sanitize_c_ident(&program.name.original),
        state_type
    );
    c_writeln!(
        out,
        "    if (hooks) {{ s->rbcpp_target = *hooks; }} else {{ memset(&s->rbcpp_target, 0, sizeof(s->rbcpp_target)); }}"
    );
    c_writeln!(out, "    s->rbcpp_target_ctx = ctx;");
    c_writeln!(out, "}}");

    c_writeln!(out);
    c_writeln!(
        out,
        "void {}_warm_restart({} *s) {{",
        sanitize_c_ident(&program.name.original),
        state_type
    );
    for (var, retain) in program_vars_with_retain(program, project) {
        if retain != Some(RetainKind::Retain) {
            emit_state_initialization(&mut out, var, project);
        }
    }
    c_writeln!(out, "}}");

    emit_retain_functions(&mut out, program, project, &state_type);
    emit_target_sync_functions(&mut out, program, project, &state_type);
    emit_access_path_services(&mut out, program, project, &state_type);

    c_writeln!(out);
    c_writeln!(
        out,
        "void {}_scan({} *s) {{",
        sanitize_c_ident(&program.name.original),
        state_type
    );
    c_writeln!(
        out,
        "    rbcpp_scan_context rbcpp_scan = {{ s->rbcpp_cycle, RBCPP_CYCLE_MS, 0 }};"
    );
    c_writeln!(
        out,
        "    if (s->rbcpp_target.time_ms) {{ rbcpp_scan.monotonic_ms = s->rbcpp_target.time_ms(s->rbcpp_target_ctx); }}"
    );
    c_writeln!(
        out,
        "    if (s->rbcpp_target.begin_scan) {{ s->rbcpp_target.begin_scan(s->rbcpp_target_ctx, &rbcpp_scan); }}"
    );
    c_writeln!(
        out,
        "    {}_sync_inputs(s);",
        sanitize_c_ident(&program.name.original)
    );
    emit_temp_initialization(&mut out, program, project);
    let mut var_types = program_vars_with_retain(program, project)
        .into_iter()
        .map(|(var, _)| (var.name.canonical.clone(), var.type_spec.clone()))
        .collect::<std::collections::BTreeMap<_, _>>();
    for var in program.variable_declarations() {
        var_types
            .entry(var.name.canonical.clone())
            .or_insert_with(|| var.type_spec.clone());
    }
    if statements_need_il_accumulator(&program.body.statements) {
        c_writeln!(out, "    int64_t rbcpp_acc = 0;");
    }
    if let Some(sfc) = &program.body.sfc {
        emit_sfc_scan(&mut out, sfc, &var_types, project);
    } else {
        for statement in &program.body.statements {
            emit_statement(&mut out, statement, 1, &var_types, project);
        }
    }
    c_writeln!(
        out,
        "    {}_sync_outputs(s);",
        sanitize_c_ident(&program.name.original)
    );
    c_writeln!(
        out,
        "    if (s->rbcpp_target.watchdog_pet) {{ s->rbcpp_target.watchdog_pet(s->rbcpp_target_ctx, &rbcpp_scan); }}"
    );
    c_writeln!(
        out,
        "    if (s->rbcpp_target.end_scan) {{ s->rbcpp_target.end_scan(s->rbcpp_target_ctx, &rbcpp_scan); }}"
    );
    c_writeln!(out, "    s->rbcpp_cycle += 1;");
    c_writeln!(out, "}}");

    out.check()?;
    let output_len = out.len();
    let _ = out;

    if output_len > options.implementation.max_generated_c_bytes {
        return Err(CEmitError::Diagnostics(vec![Diagnostic::error(
            DiagnosticCode::Compliance,
            format!(
                "generated C size {} bytes exceeds maximum {}",
                output_len, options.implementation.max_generated_c_bytes
            ),
            None,
        )]));
    }

    Ok(COutput {
        filename_hint: format!("{}.c", sanitize_c_ident(&program.name.original)),
        source,
    })
}

mod addressing;
mod expressions;
mod fb;
mod functions;
mod state;

#[cfg(test)]
mod tests;

use addressing::*;
use expressions::*;
use functions::*;
use state::*;
